fix(playground): Use required root_hash options (#452)
## 📝 Summary

As part of #429 the check was added to prevent start-up if the
`root_hash_use_sparse_trie` and `root_hash_compare_sparse_trie` values
weren't set correctly. This updates those values for the playground (I'm
not sure if we want to update other config examples as well).

## 💡 Motivation and Context

Without this change `cargo run --bin rbuilder run
config-playground.toml` (correctly) fails with:

```
Error: root_hash_use_sparse_trie=true and root_hash_compare_sparse_trie=false must be set, otherwise node will produce incorrect blocks or confusing error messages. These settings are enforced temporarily because upstream parallel root hash implementation is not correct.

Location:
    crates/rbuilder/src/live_builder/base_config.rs:303:13
```

---

## ✅ I have completed the following steps:

* [ ] Run `make lint`
* [ ] Run `make test`
* [ ] Added tests (if applicable)